### ISSUE TITLE
can't find 'AMR' AF in gnomad_db_v3.1.2

### ISSUE THREAD

**Issue by loverlyday** [KalinNonchev/gnomAD_DB#19]
hello,
 when i use the gnomad_db_v3.1.2 ,i can't find the 'AMR' AF in the resluts, how can i get it from gnomad_db_v3.1.2 database?

thanks

**Comment by KalinNonchev** [comment]
Hello @loverlyday 
[here](https://github.com/KalinNonchev/gnomAD_DB/blob/master/gnomad_db/pkgdata/gnomad_columns.yaml) you can find the 23 columns, which I extracted from the gnomAD vcf file and inserted into the SQL database.
Indeed, "AMR" is not part of it.
`INFO=<ID=AF_amr,Number=A,Type=Float,Description="Alternate` allele frequency in samples of Latino ancestry">

1) You can recreate the SQL database by yourself by following [these steps](https://github.com/KalinNonchev/gnomAD_DB/tree/master/scripts) and including `- AF_amr` [here](https://github.com/KalinNonchev/gnomAD_DB/blob/master/gnomad_db/pkgdata/gnomad_columns.yaml).
2) You can use `AF_popmax` from the already existing SQL database to approximate the upper bound of the AF

**Comment by pkiehl2002** [comment]
Hello, 
I tried to follow these instructions to make a SQL database with additional population data. However, the Snakemake program only outputted createTSVtables.ipynb and 15G of .tsv.gz files (most of which "finished" at the same timestamp). It did not output the SQL database or insertVariants.ipynb. No errors were thrown, and there is space for the database to be made. How can I fix this?
Thank you!

**Comment by KalinNonchev** [comment]
Hello @pkiehl2002,

Here you specify the location of the database: https://github.com/KalinNonchev/gnomAD_DB/blob/master/script_config.yaml
By default it is: test_out

Can you find it there?

**Comment by KalinNonchev** [comment]
Please open an issue next time to continue the discussion as your problem is not related to the one above.
