### ISSUE TITLE
Generating SQLite preprocessed files from gnomAD

### ISSUE THREAD

**Issue by brettChapman** [KalinNonchev/gnomAD_DB#21]
Hi

I'm looking at using your tool for querying a specific set of genes from gnomAD, and to change to a new gnomeAD version as needed. I'd like to create my own filtered variant set from around 400 genes to reuse as a SQLite file in my pipeline. How did you go about generating your preprocessed SQLlite files you provided in the download link here: https://zenodo.org/record/6818606/files/gnomad_db_v3.1.2.sqlite3.gz?download=1

Ultimately I'd like a variant summary TSV from the output in a small pandas dataframe of 400 genes from gnomAD, to cross check with our internal database and also cross check against Clinvar.

Thanks.

**Comment by KalinNonchev** [comment]
Please don't hesitate to reopen this GitHub issue if you have any more questions or need further assistance.
