### ISSUE TITLE
Simultaneously upload gnomAD v4.0.0 wgs and wes file 

### ISSUE THREAD

**Issue by heomanism** [KalinNonchev/gnomAD_DB#26]
Helllo, I want to use combined values in gnomAD v4.0.0 (wgs & wes) file. 

Is there any method for doing this ?

**Comment by KalinNonchev** [comment]
Hello @heomanism,

Thank you for your question.
You can download both WGS and WES and query them together and concatenate the output.
Something like:
```python
database_location_WGS = "database_location_WGS"
database_location_WES = "database_location_WGS"
db_WGS = gnomAD_DB(database_location_WGS, gnomad_version="v4")
db_WES = gnomAD_DB(database_location_WES, gnomad_version="v4")

res_WGS = db_WGS.get_info_from_str("21:9825790:C>T", "AF")
res_WES = db_WES.get_info_from_str("21:9825790:C>T", "AF")

pandas.merge([res_WGS, res_WES]) # please adjust this, probably you would have to rename values
```

**Comment by heomanism** [comment]
Thank you for quick answer :) 

However, I want values the sum of the WGS and WES results, like the Total column in this image! 

If not available, I will calculate it based on your code for each value :)

![image](https://github.com/KalinNonchev/gnomAD_DB/assets/87968423/1dde1e82-dbf5-4c9c-ac9f-1caa695ac9bf)

**Comment by KalinNonchev** [comment]
You'll need to calculate it on your own. Thank you for the question, and please don't hesitate to reopen or raise new issues if you have more questions.

**Comment by heomanism** [comment]
Hello, I try to calculate allele frequency in each ancestry using WGS + WES data.

But, I need allele number of each ancestry, but gnomAD_DB give me only allle frequency(AF) of each ancestry only.
