### ISSUE TITLE
Missing variant in Gnomad4 but in Gnomad3

### ISSUE THREAD

**Issue by lbundalian** [KalinNonchev/gnomAD_DB#27]
I have downloaded the Gnomad3 and 4 version from here. However, I have seen some variants which can be found in Gnomad3 but not in 4 which should be the other way around, as 4 is also 3 + the new variants found with additional sequencing

**Comment by KalinNonchev** [comment]
Hello @lbundalian ,
Thank you for your comment. In 4. there are additional filters, etc. Always refer to the official gnomad search engine website. Please let me know if you can see these variants in 4.0 on the website but not in the shared sql file. Please provide links

**Comment by lbundalian** [comment]
7-92134353-C-T
![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/4fe19a55-f29f-417f-b92c-d2efcdc7ca79)

versus

gnomad.sqlite3 (gnomad 4)
![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/83a3d665-59bb-4ff6-8544-edd628237a00)

**Comment by lbundalian** [comment]
some more examples:
![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/9cc6032d-3c07-45db-aa34-fca055e8480f)

**Comment by KalinNonchev** [comment]
Ok thank you. I will double check this in the next days and let you know.

**Comment by KalinNonchev** [comment]
Hello @lbundalian, it appears that the bam files were corrupted during download due to their size. I have addressed this issue in the latest commit (https://github.com/KalinNonchev/gnomAD_DB/commit/c191de411607a7c43078d980d097442db999cefe). I have recomputed the SQLite databases to ensure their integrity and you can find the new links in the README.

```python
sqlite> select * from gnomad_db where chrom = '7' and pos = 92134353;
7|92134353|C|A|PASS|1.0|152190.0|6.57073e-06|59.9396|13.3918|0.602|268.0|4.7107|1.0|68030.0|1.46994e-05|0.0|1.46994e-05|0.0|0.0|0.0
7|92134353|C|T|PASS|1.0|152190.0|6.57073e-06|59.9396|13.3918|0.602|268.0|1.707|1.0|68030.0|1.46994e-05|0.0|1.46994e-05|0.0|0.0|0.0
```

Thank you for the feedback!
