### ISSUE TITLE
Variant Not Found in sqlite3 file but found in gnomad4 web

### ISSUE THREAD

**Issue by lbundalian** [KalinNonchev/gnomAD_DB#28]
I donwloaded the latest sqlite3 version from the website but when I cross check from gnomad3 and gnomad4 i still found a few which are missing:

![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/9286bb7d-55a6-44d8-a575-db740f5f855d)

**Comment by lbundalian** [comment]
![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/50c80f6d-674f-4dcc-92ad-e95eea8d5247)

**Comment by lbundalian** [comment]
more examples
![image](https://github.com/KalinNonchev/gnomAD_DB/assets/65872998/ae9e09bd-6fa4-43e0-b7f5-b74cb07429cc)

**Comment by lbundalian** [comment]
I cross ref it with the a database online, gnomad3 and gnomad4, the LAST value is the indicator if it is found or not in gnomad4 (all these entries are found in gnomad4)

**Comment by lbundalian** [comment]
I think there are around 1.14m of them which are found in gnomad3 but not in 4

**Comment by KalinNonchev** [comment]
Hi, do you refer to WGS or WES? I can see the variant 1-24383908-G-A in WES v4, but not in WGS v4, which is correct given your screenshot reference to the [website](https://gnomad.broadinstitute.org/variant/1-24383908-G-A?dataset=gnomad_r4). 

Could you explain again about the issue? I am unsure if I understand you. Thanks.

**Comment by lbundalian** [comment]
Hello. I am using WGS v4, basically, I have a list of variants which are annotated based on gnomad v4 (whether they are observed or not in that database), so that is my baseline reference of their existence. I donwloaded the WGS v4 to check which of the previously not observed are now observed, however, when I am checking the results there are variants which are recorded to be previously listed in the database v3 but not in v4

**Comment by KalinNonchev** [comment]
But why do you expect to find 1-24383908-G-A in the WGS v4 sql database? Your reference with the website shows that it is absent in genomes.

**Comment by lbundalian** [comment]
Ok. I will check, cause I also have this other database I am looking up for the variants

**Comment by lbundalian** [comment]
Hello. I will be closing this and will use your database to align the other database that I have. Thanks a lot

**Comment by lbundalian** [comment]
Closed
