### ISSUE TITLE
Python script to collect allele frequency for batch of SNPs in gnomAD database

### ISSUE THREAD

**Issue by AR-Shicheng** [KalinNonchev/gnomAD_DB#30]
Hi Kalin, 

Do you think it is a perfect tool to fetch allele frequency data for a batch of SNPs from the gnomAD database, encompassing all populations. Ideally, this script would accept SNP IDs as input and output a data frame containing the allele frequency across different populations, along with the count of homozygous carriers.

https://www.biostars.org/p/9591727/#9591729

Thanks. 

Shicheng

**Comment by KalinNonchev** [comment]
Hi @AR-Shicheng , short answer - yes. Please take a look at [the tutorial notebook](https://github.com/KalinNonchev/gnomAD_DB/blob/master/scripts/GettingStartedwithGnomAD_DB.ipynb).
