### ISSUE TITLE
Missing rs ID and south asian allele frequency

### ISSUE THREAD

**Issue by shubham1637** [KalinNonchev/gnomAD_DB#33]
Hi, 
  I am using `gnomad_db_v3.1.2`, however I find that sqlite3 table has very limited information. It doesn't have rs id or sas allele frequency. Is there a way to get this info? should I use different database?

**Comment by KalinNonchev** [comment]
Hello @shubham1637 ,
thank you for your question. We provide only the most used annotations to keep the database size small. It is possible to include all the attributes you would need by [running this pipeline](https://github.com/KalinNonchev/gnomAD_DB/tree/master/scripts). You should add the attributes of interest [here](https://github.com/KalinNonchev/gnomAD_DB/blob/master/gnomad_db/pkgdata/gnomad_columns.yaml).

Please let me know if you have further questions.

Best,
