### ISSUE TITLE
Question about lcr and segdup

### ISSUE THREAD

**Issue by sophiezhang-origin** [KalinNonchev/gnomAD_DB#34]
Hello,

I wonder if it is possible to tell if a variant falls into LCR or SEGDUP region using gnomAD_DB? It seems like the "filter" columns does not contain "lcr" or "seddup" flag. 

Any feedback is greatly appreciated. Thank you so much in advance!

**Comment by KalinNonchev** [comment]
Hello @sophiezhang-origin ,

You can provide the regions and try 
```python
db.get_info_for_interval(chrom=21, interval_start=9825780, interval_end=9825799, query="AF")
```
You can find more information in the [tutorial](https://github.com/KalinNonchev/gnomAD_DB/blob/master/scripts/GettingStartedwithGnomAD_DB.ipynb).
